In [7]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
net = nn.Sequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))

X = torch.rand(2, 20)
net(X)

tensor([[-0.1534, -0.1098,  0.0291, -0.2254,  0.1218,  0.1092, -0.0873,  0.1512,
         -0.1569,  0.1551],
        [-0.3085,  0.0006,  0.0148, -0.1900,  0.0619,  0.1319, -0.0597,  0.0010,
         -0.0350,  0.1870]], grad_fn=<AddmmBackward0>)

In [4]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.out = nn.Linear(256, 10)
    
    def forward(self, X):
        return self.out(F.relu(self.hidden(X)))

In [9]:
net = MLP()
net(X)

tensor([[-0.0464,  0.0577,  0.2360, -0.1389, -0.2218,  0.1200, -0.0683, -0.0779,
         -0.0307, -0.0207],
        [-0.1593,  0.1679,  0.2470, -0.0861, -0.1694,  0.0865,  0.1178, -0.0323,
          0.1020, -0.0232]], grad_fn=<AddmmBackward0>)

In [12]:
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(2, 4)
net(X)

tensor([[ 0.0333],
        [-0.0945]], grad_fn=<AddmmBackward0>)

In [18]:
print(net[2].state_dict())

OrderedDict([('weight', tensor([[ 0.0003, -0.1473,  0.2795, -0.3141, -0.1986,  0.1303, -0.3036, -0.0399]])), ('bias', tensor([-0.1161]))])


In [19]:
print(*[(name, param.shape) for name, param in net[0].named_parameters()])
print(*[(name, param.shape) for name, param in net.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [20]:
net.state_dict()['2.bias'].data

tensor([-0.1161])

In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [1]:
!nvidia-smi

Tue Jul 25 23:15:32 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.72       Driver Version: 512.72       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8     5W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import time
import torch

In [79]:
device = torch.device("cuda:0")
X1 = torch.rand(1000, 1000, device=device)
X2 = torch.rand(1000, 1000)

start = time.time()
X3 = torch.matmul(X1, X1)
middle = time.time()

print(f'gpu的运行时间为{middle-start:f}s')

X4 = torch.matmul(X2, X2)
end = time.time()

print(f'cpu的运行时间为{end-middle:f}s')

gpu的运行时间为0.000000s
cpu的运行时间为0.011968s
